# https://hydra.cc/docs/plugins/colorlog/
# enable color logging
defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog

# output directory, generated dynamically on each run
run:
  dir: ${paths.log_dir}/runs/${now:%Y-%m-%d}_${now:%H_%M}
sweep:
  dir: ${paths.log_dir}/multiruns/${now:%Y-%m-%d}_${now:%H_%M}
  subdir: ${hydra.job.num}
