name: menv

channels:
  - pyg
  - pytorch
  - nvidia
  - anaconda
  - conda-forge
  - defaults

dependencies:
  - python=3.10.4
  - pip=22.2.2
  - cmake=3.20.2

  # Math and numerics
  #- numba=0.56.4
  #- numpy=1.23.3
  #- scikit-learn=1.1.2
  #- scipy=1.9.1

  # ML
  - pyg::pyg
  - pyg::pytorch-sparse
  - pyg::pytorch-cluster
  - pytorch-cuda=11.8
  - conda-forge::lightning
  - pytorch::torchaudio
  - pytorch::torchvision
  - ogb
  - conda-forge::torchmetrics
  - wandb

  # Math
  - numpy
  - scipy

  # Bio
  - biopython

  # Graph
  - networkx

  # Config
  - colorlog
  - hydra-core
  - pyyaml

  # Testing
  - icontract
  - pre-commit
  - pytest
  - typeguard

  # Other
  - filelock
  - more-itertools
  - protobuf
  - tqdm

  - pip:
      - hydra-colorlog
      - distinctipy
      - jupyterlab
