name: cenv

channels:
  - pyg
  - pytorch
  - nvidia
  - anaconda
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip
  - cmake

  # ML
  - pytorch::pytorch-cuda
  - pytorch::torchaudio
  - pytorch::torchvision
  - pyg::pyg
  - wandb

  # Stats
  - numpy
  - scipy
  - pandas

  # Bio
  - biopython

  # Graph
  - networkx

  # Config
  - colorlog
  - dataclass-wizard
  - hydra-core
  - pyyaml

  # Testing
  - icontract
  - pre-commit
  - pytest
  - pytest-xdist
  - typeguard

  # Other
  - filelock
  - more-itertools==10.0.0
  - protobuf
  - tqdm

  - pip:
      - hydra-colorlog
      - distinctipy
      - jupyterlab
