name: menv

channels:
  - pyg
  - pytorch
  - nvidia
  - anaconda
  - conda-forge
  - defaults

dependencies:
  - python=3.10.4
  - pip=22.2.2
  - cmake=3.20.2

  # Math and numerics
  #- numba=0.56.4
  #- numpy=1.23.3
  #- scikit-learn=1.1.2
  #- scipy=1.9.1

  # ML
  - pytorch::pytorch=2.0.1
  - pytorch::pytorch-cuda=11.8
  - pytorch::torchaudio=2.0.2
  - pytorch::torchvision=0.15.2
  - pyg::pyg=2.3.1
  - pyg::pytorch-sparse=0.6.18
  - pyg::pytorch-cluster=1.6.3
  - conda-forge::lightning=2.1.0
  - ogb
  - conda-forge::torchmetrics=1.2.0
  - wandb

  # Math
  - numpy
  - scipy

  # Bio
  - biopython

  # Graph
  - networkx

  # Config
  - colorlog
  - dataclass-wizard
  - hydra-core
  - pyyaml

  # Testing
  - icontract
  - pre-commit
  - pytest
  - typeguard

  # Other
  - filelock
  - more-itertools==10.0.0
  - protobuf
  - tqdm

  - pip:
      - hydra-colorlog
      - distinctipy
      - jupyterlab
