# This is a template config for generating random reference genome
# Generated data is saved to $PROJECT_ROOT/data/reference/${species_name}.
# Each chromosome is saved in separate file, eg. chr1.fasta, chr2.fasta...
chromosomes:
  chr1: 10000000 # size order of E Coli genome

gc_content: 0.44 # Percentage of G and C bases. Specify as float in range [0., 1.).
real_data: # set to True if this is config describing non-simulated dataset
