# This is a template config for generating random reference genome
# Generated data is saved to $PROJECT_ROOT/data/reference/${species_name}.
# Each chromosome is saved in separate file, eg. chr1.fasta, chr2.fasta...
chromosomes: # size order of L. Esculentum genome
  chr1: 1000000000
  chr2: 1000000000
  chr3: 1000000000
  chr4: 1000000000
  chr5: 1000000000

gc_content: 0.44 # Percentage of G and C bases. Specify as float in range [0., 1.).
real_data: # set to True if this is config describing non-simulated dataset
