name: homo_sapiens
release: "chm13_v2" # either chm13_v2 or chm13_v1_1
keep_metadata: true # keep downloaded files
store_artifacts: false # wandb logging, need to set up wandb access on the machine first
