name: homo_sapiens
release: "repeat_v4"

mode: complex

p_choices: [0.5, 0.25, 0.25] # DELETE INSERT MUTATE probabilities
mutation_rates:
  start: 0.001
  stop: 0.0105
  step: 0.001

chr_src_path: ${paths.ref_dir}/homo_sapiens/chm13_v2/chromosomes/
# include: ["chr1.fasta"] uncommenting will include chr1 only
exclude: ["chrX.fasta", "chrY.fasta"]
chr_src_seed: 100
sequence_len: 1000000 # starting sequence length for chromosome

keep_metadata: false
store_artifacts: false
