name: db_graph
graph_type: # either digraph or multigraph, currently ignored an creating both types
set:
  name: # designator that is going to be appended to experiment directory
  dir_filter: # regex filter to match the assemblies projects that should go into this training set
mult_info_path: # Placeholder
gfa_path: # Placeholder
#supported features for digraph (edge is just a k-mer):
# kc - coverage
# ln - length, i.e. number of nucleotides in node
# in_degree - input degree of nodes
# out_degree - out degree of nodes
# pr_N - k-step PageRank where N represent number of hops (supported up to N = 5)
# For now coverage (col0) and length (col1) are always added and used
features: [kc, ln, in_degree, out_degree, pr_2]
k: 501
debug: True # if true outputs the graph in GML format for visualization purposes