name: pbsim2
params:
  long: # command line params starting with --
    depth: 30
    hmm_model: ${project_root:vendor/pbsim2/data/P6C4.model} # either use absolute path or use ${project_root} resolver
    accuracy-mean: 0.95
  
suffix: ['.fastq'] # list of file suffixes to match when searching for reference

species: random_species # name of the reference species
request: # request number of simulations for specific chromosomes in reference
  chr1: 4
