name: pbsim2
overwrite: True # set to False if you want to keep existing data

params:
  long: # command line params starting with --
    depth: 20
    hmm_model: ${project_root:vendor/pbsim2/data/P6C4.model} # either use absolute path or use ${project_root} resolver
    accuracy-mean: 0.99
  
suffix: ['.fa', '.fasta'] # list of file suffixes to match when searching for reference

request: # request number of simulations for specific chromosomes in reference
  chr1: 1
