name: pbsim3

profiles:
  test:
  train:
  val:

params:
  long: # command line params starting with --
    depth: 25
    strategy: wgs
    method: sample
    sample-profile-id: # make sure that the id matches one in the profile path
    seed: null
    prefix: sim

profile:
  path: ${project_root:pf} # path to the profile directory
