name: pbsim2
overwrite: True # set to False if you want to keep existing data
threads: 7 # set if you want to override (default is os.cpu_count() - 1)

params:
  long: # command line params starting with --
    depth: 20
    hmm_model: ${project_root:vendor/pbsim2/data/P6C4.model} # either use absolute path or use ${project_root} resolver
    accuracy-mean: 1.00

suffix: [".fa", ".fasta"] # list of file suffixes to match when searching for reference
