# this is top-level default config for assembly step
# We need to provide the reads as well as the reference data in order to
# be able to generate all the output files required for the downstream tasks
# The reference path is constructed from paths.ref_dir and species name
# Reads paths is constructed from reads_dir and species name

defaults:
  - hydra: hydra
  - paths: paths
  - asm: la_jolla
  - _self_
