# this is top-level default config
defaults:
  - reference: random_species
  - reads: pbsim2
  - asm: la_jolla
  - graph: db_graph
  - _self_


# combine
reference:
  overwrite: True
  name: random_species_${now:%m_%d}
reads:
  request:
    chr1: 2
    chr2: 2
asm:
  experiment: random_species_${now:%m_%d}
graph:
  overwrite: True