# this is top-level default config
defaults:
  - hydra: hydra
  - paths: paths
  - reference: reference
  - reads: pbsim3
  - asm: la_jolla
#  - graph: db_graph
  - _self_

species_name: random_species
seed: 42

# combine
reference:
  overwrite: True
asm:
  experiment: ${species_name}_${now:%m_%d}
#graph:
#  experiment: ${species_name}_${now:%m_%d}
#  overwrite: True