# this is top-level default config
defaults:
  - reference: random_species
  - reads: pbsim2
  - asm: la_jolla
  - graph: db_graph
  - _self_


# combine
reference:
  overwrite: False
reads:
  overwrite: True
asm:
  overwrite: True
graph:
  overwrite: True