# asm_path: /home/msimunovic/ws/genomic/curly-octo-train/data/assemblies/random_species_medium_c1/01_21/S3/chr1/
asm_path: /home/msimunovic/ws/genomic/curly-octo-train/data/assemblies/chr_11_homunculus_50M/12_04/S100/chr2/  # eval_01/alignments.tx
full_asm_subdir: full_asm
eval_stage: eval_00
k: 501
threads: null
output_path: /tmp