# This is top-level default config for graph conversion step

defaults:
  - hydra: hydra
  - paths: paths
  - species_name@_global_: random_species
  - graph: db_graph
  - _self_

date_mm_dd: ${now:%m_%d}
experiment: ${species_name}
graph: 
  set:
    name: train
    dir_filter:

tags: # list of tags that describe additionaly the experiment
