# path to root directory
# PROJECT_ROOT environment variable is defined in .env file in root of the project
# VS Code will pick this up automatically otherwise it needs to be defined before
# running the script, e.g. PROJECT_ROOT="$HOME/ws/project" python src/train.py
root_dir: ${oc.env:PROJECT_ROOT}

# path to data directory
data_dir: ${paths.root_dir}/data/
# path to genome references
ref_dir: ${paths.root_dir}/data/references/
# path to simulated reads
simulated_data_dir: ${paths.root_dir}/data/simulated

# path for storing the outputs of the specific run
# see hydra config for the exact format used
output_dir: ${hydra:runtime.output_dir}

# path to logging directory
log_dir: ${paths.root_dir}/logs/

