name: LJA
overwrite: True # set to False if you want to keep existing data

params:
  long:
    threads: 15
    reference: # ${paths.ref_dir}/${species_name}/
  short:
    k: 501 
    # K: 2001 # not supported for jumboDBG
  append:
    "--compress"

keep: ["graph.gfa", "mult.info", "ref.info"]
exec: jumboDBG # name of the executable to use (jumboDBG or lja)

dir_filter: # regex expression to filter out non-matching reads